# Generated by Django 4.1.2 on 2022-10-07 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="upload_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="upload_image",
            field=models.ImageField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
    ]
