# Generated by Django 4.1.2 on 2022-10-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_image_image_image_upload_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="upload_image",
            field=models.ImageField(upload_to="media/%Y/%m/%d/"),
        ),
    ]
