# Generated by Django 4.1.2 on 2022-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_image_upload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="upload_image",
            field=models.FileField(upload_to="media/%Y/%m/%d/"),
        ),
    ]
