# Generated by Django 4.1.2 on 2022-10-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_image_upload_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="upload_date",
        ),
    ]
